name: Update Posts
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-posts:
    name: Update Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://akko.netlify.app/feed.xml"
          max_post_count: "3"
