name: Update Posts

on:
  schedule:
    - cron: "0 0 * * *" # 每天零点执行一次
  workflow_dispatch: # 同时支持手动触发

permissions:
  contents: write

jobs:
  update-posts:
    name: Update Posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.0'

      - name: Pull posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://akko.netlify.app/archives/"
        
